import { promises as fsp } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

/**
 * Installs a Claude Code `Notification` hook into the user's global
 * ~/.claude/settings.json so that external (terminal) sessions can tell this app
 * when they are blocked waiting on the user.
 *
 * Claude Code fires the Notification hook exactly when it needs input — for a
 * tool-permission prompt and for idle-waiting (matcher values `permission_prompt`
 * / `idle_prompt`). Our hook command runs a tiny Node helper that appends a
 * record to ~/.claude/wotch/notifications.jsonl; ExternalSessionTracker tails
 * that log and marks the matching session as "needs attention".
 *
 * The helper is written to disk by the installer (rather than bundled as a
 * packaged resource) so the absolute path is stable across dev/prod and the
 * hook command — `node "<path>"` — works on every host without asar gymnastics.
 *
 * Everything here mutates the user's *global* settings, so it must only run on
 * explicit opt-in from the UI. Install is idempotent; uninstall removes only the
 * entry we added, leaving any user-authored hooks untouched.
 */

export const WOTCH_DIR = join(homedir(), '.claude', 'wotch')
export const NOTIFICATIONS_LOG = join(WOTCH_DIR, 'notifications.jsonl')
const HELPER_PATH = join(WOTCH_DIR, 'notify-hook.mjs')
const SETTINGS_PATH = join(homedir(), '.claude', 'settings.json')

/** Marker substring used to recognize our hook command on (un)install. */
const HOOK_MARKER = 'notify-hook.mjs'

interface HookCommand {
  type?: string
  command?: string
  [k: string]: unknown
}
interface HookMatcher {
  matcher?: string
  hooks?: HookCommand[]
  [k: string]: unknown
}
interface ClaudeSettings {
  hooks?: { Notification?: HookMatcher[]; [k: string]: unknown }
  [k: string]: unknown
}

// The helper source. Reads the hook payload JSON from stdin and appends a
// compact record. Best-effort — any failure is swallowed so the hook can never
// disrupt the host session.
const HELPER_SOURCE = `// Generated by WotchCode — Claude Code Notification hook helper.
// Appends a record to notifications.jsonl when Claude needs the user, so the
// WotchCode app can mark the session as needing attention. Safe to delete; the
// app rewrites it when attention alerts are (re)enabled.
import { appendFile, mkdir } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'

const chunks = []
process.stdin.on('data', (c) => chunks.push(c))
process.stdin.on('end', async () => {
  try {
    const raw = Buffer.concat(chunks).toString('utf8').trim()
    const payload = raw ? JSON.parse(raw) : {}
    const sessionId = payload.session_id || payload.sessionId
    if (!sessionId) return
    const message = typeof payload.message === 'string' ? payload.message : ''
    const rawType = String(payload.notification_type || payload.notificationType || '')
    const isPermission =
      /permission/i.test(rawType) || /permission|approve|approval|tool/i.test(message)
    const type = isPermission ? 'permission' : 'idle'
    const dir = join(homedir(), '.claude', 'wotch')
    await mkdir(dir, { recursive: true })
    const line = JSON.stringify({ sessionId, type, message, ts: Date.now() }) + '\\n'
    await appendFile(join(dir, 'notifications.jsonl'), line, 'utf8')
  } catch {
    // ignore — never break the host session
  }
})
`

function hookCommand(): string {
  return `node "${HELPER_PATH}"`
}

function isOurCommand(h: HookCommand): boolean {
  return typeof h.command === 'string' && h.command.includes(HOOK_MARKER)
}

function matcherHasOurs(m: HookMatcher): boolean {
  return Array.isArray(m.hooks) && m.hooks.some(isOurCommand)
}

async function readSettings(): Promise<ClaudeSettings> {
  let text: string
  try {
    text = await fsp.readFile(SETTINGS_PATH, 'utf8')
  } catch {
    return {} // missing file → fresh settings
  }
  const trimmed = text.trim()
  if (!trimmed) return {}
  try {
    return JSON.parse(trimmed) as ClaudeSettings
  } catch (e) {
    // Don't clobber a settings file we can't parse — surface instead.
    throw new Error(
      `Could not parse ${SETTINGS_PATH} (not valid JSON). Fix or remove it, then retry. (${
        e instanceof Error ? e.message : String(e)
      })`
    )
  }
}

async function writeSettings(settings: ClaudeSettings): Promise<void> {
  await fsp.mkdir(join(homedir(), '.claude'), { recursive: true })
  await fsp.writeFile(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n', 'utf8')
}

export async function isNotificationHookInstalled(): Promise<boolean> {
  try {
    const settings = await readSettings()
    const list = settings.hooks?.Notification
    return Array.isArray(list) && list.some(matcherHasOurs)
  } catch {
    return false
  }
}

export async function installNotificationHook(): Promise<void> {
  await fsp.mkdir(WOTCH_DIR, { recursive: true })
  await fsp.writeFile(HELPER_PATH, HELPER_SOURCE, 'utf8')

  const settings = await readSettings()
  const hooks = (settings.hooks ??= {})
  const list = Array.isArray(hooks.Notification) ? hooks.Notification : (hooks.Notification = [])
  const command = hookCommand()

  let found = false
  for (const m of list) {
    if (!matcherHasOurs(m)) continue
    found = true
    // Refresh in case the home dir / path changed since last install.
    for (const h of m.hooks ?? []) if (isOurCommand(h)) h.command = command
  }
  if (!found) {
    list.push({ matcher: '', hooks: [{ type: 'command', command }] })
  }
  await writeSettings(settings)
}

export async function uninstallNotificationHook(): Promise<void> {
  const settings = await readSettings()
  const list = settings.hooks?.Notification
  if (!Array.isArray(list)) return
  const next: HookMatcher[] = []
  for (const m of list) {
    if (!Array.isArray(m.hooks)) {
      next.push(m)
      continue
    }
    const keptHooks = m.hooks.filter((h) => !isOurCommand(h))
    if (keptHooks.length === 0 && matcherHasOurs(m)) {
      // This matcher existed only for our command — drop it entirely.
      continue
    }
    next.push({ ...m, hooks: keptHooks })
  }
  if (next.length > 0) settings.hooks!.Notification = next
  else delete settings.hooks!.Notification
  await writeSettings(settings)
}
